=== kankoli/to-do-manager/todo_53V3N/todoManagerData.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


<!-- See http://www.w3schools.com/schema/schema_example.asp -->

<!-- definition of simple elements -->
<xs:element name="name" type="xs:string"/>
<xs:element name="date" type="xs:dateTime"/>
<xs:element name="priority" type="xs:string"/>
<xs:element name="completed" type="xs:string"/>
<xs:element name="category" type="xs:string"/>
<xs:element name="description" type="xs:string"/>
<xs:element name="urgent" type="xs:string"/>
<xs:element name="color" type="xs:string"/>

<!-- definition of complex elements -->
<xs:element name="todoManagerData">
  <xs:complexType>
    <xs:sequence>          
      <xs:element name="tasks">
        <xs:complexType>
          <xs:sequence>          
            <xs:element name="task" minOccurs = "0" maxOccurs="unbounded">
              <xs:complexType>
                <xs:sequence>          
                  <xs:element ref="name"/>
                  <xs:element ref="date"/>
                  <xs:element ref="priority"/>
                  <xs:element ref="completed"/>
                  <xs:element ref="category"/>
                  <xs:element ref="description"/>
                  <xs:element ref="urgent"/>
                </xs:sequence>
              </xs:complexType>
      		</xs:element>    
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      
 	  <!-- Not ready yet -->	     
      <xs:element name="categories">
        <xs:complexType>
          <xs:sequence>          
            <xs:element name="category" minOccurs = "0" maxOccurs="unbounded">  
              <xs:complexType>
    		    <xs:sequence>
                  <xs:element ref="name"/>
                  <xs:element ref="color"/>
			    </xs:sequence>
  			  </xs:complexType>
      		</xs:element>    
          </xs:sequence>
        </xs:complexType>      
      </xs:element>

    </xs:sequence>          
  </xs:complexType>
</xs:element>
</xs:schema>

=== kankoli/to-do-manager/todo_53V3N/todoManagerData.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoManagerData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="todoManagerData.xsd">
  <tasks>
    <task>
      <name>Task1</name>
      <date>2013-01-24T22:30:00.000+01:00</date>
      <priority>LOW</priority>
      <completed>false</completed>
      <category>Sport</category>
      <description />
    </task>
    <task>
      <name>Task2</name>
      <date>2013-01-26T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>true</completed>
      <category>jshkshkf</category>
      <description />
    </task>
    <task>
      <name>ciao</name>
      <date>2013-01-27T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>false</completed>
      <category>Sport</category>
      <description>this is new!</description>
    </task>
    <task>
      <name>Task0</name>
      <date>2013-01-27T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>false</completed>
      <category>fun</category>
      <description />
    </task>
    <task>
      <name>New task!</name>
      <date>2013-01-31T17:45:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>false</completed>
      <category>meeting</category>
      <description>some brief text.</description>
    </task>
    <task>
      <name>aaaaa</name>
      <date>2013-02-22T12:43:06.797+01:00</date>
      <priority>NORMAL</priority>
      <completed>false</completed>
      <category>kfjsdkfs</category>
      <description>bla bla bla a description</description>
    </task>
  </tasks>
  <categories>
    <category>
      <name>kfjsdkfs</name>
      <color>-11867345</color>
    </category>
    <category>
      <name>meeting</name>
      <color>-7283286</color>
    </category>
    <category>
      <name>jshkshkf</name>
      <color>-4000695</color>
    </category>
    <category>
      <name>Sport</name>
      <color>-14752099</color>
    </category>
    <category>
      <name>fun</name>
      <color>-9916485</color>
    </category>
    <category>
      <name>Prova</name>
      <color>-1104603</color>
    </category>
  </categories>
</todoManagerData>

=== kankoli/to-do-manager/todo_53V3N/Copy of todoManagerData.xml
<?xml version="1.0" encoding="UTF-8"?>
<todoManagerData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="todoManagerData.xsd">
  <tasks>
    <task>
      <name>ciao</name>
      <date>2013-01-27T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>true</completed>
      <category>Sport</category>
      <description>this is new!</description>
      <urgent>false</urgent>
    </task>
    <task>
      <name>A good name!</name>
      <date>2013-01-31T17:45:00.000+01:00</date>
      <priority>LOW</priority>
      <completed>false</completed>
      <category>Test</category>
      <description>some brief text.sfksfskfjskfskdfsdkfjskdhfskdskdfskjfdsklfjskdljfksdljflsdkjlsdjfsdljfsdlfjsdljsdlfjdslfjsdlfjsdljfsldjdlsjflsdkjfldsjfldsjfldsjfdkls</description>
      <urgent>false</urgent>
    </task>
    <task>
      <name>Hi 3</name>
      <date>2013-02-20T12:30:00.000+01:00</date>
      <priority>NORMAL</priority>
      <completed>false</completed>
      <category>Meeting</category>
      <description>this is new!</description>
      <urgent>false</urgent>
    </task>
    <task>
      <name>Hi2</name>
      <date>2013-02-21T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>true</completed>
      <category>Fun</category>
      <description>this is new!</description>
      <urgent>true</urgent>
    </task>
    <task>
      <name>H4i</name>
      <date>2013-02-23T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>false</completed>
      <category>Sport</category>
      <description>this is new!</description>
      <urgent>false</urgent>
    </task>
    <task>
      <name>Hi</name>
      <date>2013-02-27T12:30:00.000+01:00</date>
      <priority>HIGH</priority>
      <completed>false</completed>
      <category>Fun</category>
      <description>this is new!</description>
      <urgent>false</urgent>
    </task>
    <task>
      <name>Hi</name>
      <date>2013-02-27T12:30:00.000+01:00</date>
      <priority>LOW</priority>
      <completed>false</completed>
      <category>Fun</category>
      <description>this is new!</description>
      <urgent>true</urgent>
    </task>
  </tasks>
  <categories>
    <category>
      <name>Fun</name>
      <color>-9916485</color>
    </category>
    <category>
      <name>Test</name>
      <color>-1104603</color>
    </category>
    <category>
      <name>Meeting</name>
      <color>-7283286</color>
    </category>
    <category>
      <name>Sport</name>
      <color>-14752099</color>
    </category>
  </categories>
</todoManagerData>
